# --- !Ups

create table "PROJECT" (
    "ID" INT NOT NULL AUTO_INCREMENT            ,
    "NAME" VARCHAR NOT NULL,
    PRIMARY KEY (ID)
);

create table "URL" (
    "ID" INT NOT NULL AUTO_INCREMENT,
    "NAME" VARCHAR NOT NULL,
    "ADDRESS" VARCHAR NOT NULL,
    "PROJECT_ID" INT NOT NULL,
    "HTTP_METHOD" VARCHAR NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID) ON DELETE CASCADE
);

create table "URL_RECORD" (
    "ID" INT NOT NULL AUTO_INCREMENT,
    "CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "RESPONSE_TIME" FLOAT NOT NULL,
    "URL_ID" INT NOT NULL,
    "STATUS" VARCHAR,
    PRIMARY KEY (ID),
    FOREIGN KEY (URL_ID) REFERENCES URL(ID) ON DELETE CASCADE
);

# --- !Downs

drop table "URL";
drop table "PROJECT";
drop table "URL_RECORD";